# Paths
path: C:/Users/USER/Downloads/train-yolov8-custom-dataset-step-by-step-guide/prepare_data/data
train: C:/Users/USER/Downloads/train-yolov8-custom-dataset-step-by-step-guide/prepare_data/data/train/images
val: C:/Users/USER/Downloads/train-yolov8-custom-dataset-step-by-step-guide/prepare_data/data/validation/images

# Classes
names:
  0: alpaca